---
title: "Compare Rates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Compare Rates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(uxr)
```

## Compare Rates Between Groups

```{r}
design = c("A","B")
complete = c(37, 22)
incomplete = c(418, 416)
data <- data.frame(design, complete, incomplete)
data <- data |> tidyr::pivot_longer(!design, names_to = "rate", values_to = "n") |>  tidyr::uncount(n)

data

```

```{r}
design_a <- filter(data, design == "A")
design_b <- filter(data, design == "B")

data.frame(design_a, design_b)
```


```{r}
test_n_1_prop(data, design, rate)
```
test_n_1_prop(data, design, rate, conf_level = 0.90) 


compare_rates_between_groups(data, )
```

```{r}

```



## Compare Rates Within Groups

```{r}

A <- c(1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1)
B <- c(0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0)

data <- data.frame(A, B)

```


```{r}
compare_rates_within_groups(data, A, B)
```


