---
title: "Compare Means"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Compare Means}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ''
)
```

## Compare Means Within Groups

This uses a paired t-test.

```{r}
# Example data
data <- data.frame(id = c(1:7),
           task1 = c(4, 1, 2, 3, 8, 4, 4),
           task2 = c(7, 13, 9, 7, 18, 8, 10))

data 
```


```{r}
#| eval: false
compare_means_within_groups(data$task1, data$task2)
```

```{bash}
#| eval: false

── Compare Means Within Groups ────────────────────────────────────────────────────────────────────
  X.                result.estimate  
  mean.difference         -6.571429  
  t                           -5.18  
  p                           0.002  
  df                              6  
  ci_level                     0.95  
  lower_ci                    -9.68  
  upper_ci                    -3.46  

```

## Compare Means Between Groups


### Welsch Test


```{r}
data <- tibble::tribble(~old, ~new,
                18, 12,
                44, 35, 
                35, 21,
                78, 9,
                38, 2, 
                18, 10,
                16, 5,
                22, 38,
                40, 30,
                77, NA,
                20, NA)

data2 <- data |> 
  tidyr::pivot_longer(cols = everything(), names_to = "group", values_to = "value")
```

```{r}
#| eval: false
compare_means_between_groups(data2, value, group, c("old", "new"), equal_variances = FALSE)
```

```{bash}
#| eval: false

── Welch Two Sample t-test ─────────────────────────────────────────────────────────────────────────────────
  X.                  result.estimate  
  mean.in.group.new                18  
  mean.in.group.old          36.90909  
  t                             -2.33  
  p                             0.033  
  df                          16.7007  
  ci_level                       0.95  
  lower_ci                     -36.04  
  upper_ci                      -1.78  
```
